### ISSUE TITLE
Not all sound files are used.

### ISSUE THREAD

**Issue by Charlieee1** [thekevinlab/keypress#2]
I noticed in the code that whether the key was pressed or released, the same audio files would be played. The up files are never played.
`def on_press(self, key):        
        if key != self.last_pressed:
            key_type = self.get_key_type(key)

            files = glob.glob('soundpack/{0}/down/*.mp3'.format(key_type))
            playsound(random.choice(files), block=False)

            self.last_pressed = key

    def on_release(self, key) -> Any:
        key_type = self.get_key_type(key)

        files = glob.glob('soundpack/{0}/down/*.mp3'.format(key_type))
        playsound(random.choice(files), block=False)

        self.last_pressed = None

**Comment by thekevinlab** [comment]
It should be fixed now.
